// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyABpXPwnw09m7L6zEhg6Q__WO3j98puEn0',
    appId: '1:860523175980:web:8bae96bf0fef88cebff189',
    messagingSenderId: '860523175980',
    projectId: 'flutter-login-1a429',
    authDomain: 'flutter-login-1a429.firebaseapp.com',
    storageBucket: 'flutter-login-1a429.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDWfbhmb15J0ta0Y-xfYvktTwf2-dNqkEE',
    appId: '1:860523175980:android:449937a72f5749c6bff189',
    messagingSenderId: '860523175980',
    projectId: 'flutter-login-1a429',
    storageBucket: 'flutter-login-1a429.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCY9o08HZrmHfkLNamgjR2niDudd8wppyk',
    appId: '1:860523175980:ios:4e90355eebb61c7cbff189',
    messagingSenderId: '860523175980',
    projectId: 'flutter-login-1a429',
    storageBucket: 'flutter-login-1a429.appspot.com',
    iosClientId: '860523175980-kno5ikqekh0ivfpe1140q9r8pdnkc6d5.apps.googleusercontent.com',
    iosBundleId: 'com.example.absensi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCY9o08HZrmHfkLNamgjR2niDudd8wppyk',
    appId: '1:860523175980:ios:4e90355eebb61c7cbff189',
    messagingSenderId: '860523175980',
    projectId: 'flutter-login-1a429',
    storageBucket: 'flutter-login-1a429.appspot.com',
    iosClientId: '860523175980-kno5ikqekh0ivfpe1140q9r8pdnkc6d5.apps.googleusercontent.com',
    iosBundleId: 'com.example.absensi',
  );
}
